### ISSUE TITLE
name conflict with existing program

### ISSUE THREAD

**Issue by professorjamesmoriarty** [SethDusek/define#1]
Hiya, trying to (well I did lol) package this for aur. Can see it here https://aur.archlinux.org/packages/whatis-git/

But it seems to conflict with any existing package that ALOT of people most likely have installed. (whatis from man-db package)

https://www.archlinux.org/packages/core/i686/man-db/files/

Is there any other names you would consider being ok to use for the "executable" name?

**Comment by sethdusek** [comment]
Name has been changed to "define". Is that okay?
