### ISSUE TITLE
Way sound is being played is not compatible with every system.

### ISSUE THREAD

**Issue by ColdSauce** [SethDusek/define#12]
I know this has been referenced in a previous issue: https://github.com/SethDusek/define/issues/5 however, the fix was add a dependency to an Arch package. For people installing this from source or people using operating systems where play is not available, that isn't an adequate fix.

Getting sound to work on every platform is a nightmare (I just tried :D ) I guess that's why libraries exist..

Here's a good page that lists a few external dependencies we could use to play sounds programatically. 

https://wiki.python.org/moin/PythonInMusic

**Comment by sethdusek** [comment]
Unfortunately the url is not opening. The original plan was to use aplay as it is included in most alsa setups but aplay does not support mp3s as far as I know

**Comment by sethdusek** [comment]
Define has now switched to gstreamer using gstreamer-launch which is available on arch in the gstreamer package and on debian and ubuntu using the gstreamer-tools package

**Comment by ColdSauce** [comment]
Awesome! Great to hear!
