### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by JohnMHarrisJr** [SethDusek/define#16]
Your current code has API keys for services used, you should either remove all such items and services. This application is infringing on the rights of users. People want to be able to freely look up a term in a dictionary of their language. The best way to do this is to use the dictionaries already present on the system.

Do not use services that log requests made by users, and, certainly, not with your API keys. Your users are not you.

**Comment by shaggytwodope** [comment]
>infringing on the rights of users

Every user has the right to use any type of software they wish. While I respect your personal view on the matter. This is only a personal view. Your concerns tho will be taken into consideration in futher development. But at this time things work fine.

Your welcome to fork the project and do this yourself however. Pull requests are welcomed.

**Comment by JohnMHarrisJr** [comment]
You missed the entire point of the issue, the issue is that he uses his personal API keys in this application.

**Comment by Diitto** [comment]
@JohnMHarrisJr LOL! As if that matters! Please learn, you fool!

**Comment by JohnMHarrisJr** [comment]
For an application created to define words, using another individual's
personal key is a serious issue. The proper way to go about this would
be to install a dictionary.

**Comment by Diitto** [comment]
Then do it yourself, silly! Are you not a developer? Or just too crappy of
one? If you don't feel like it, then don't make complaints, imbecile! :D

On Saturday, September 12, 2015, John M. Harris, Jr. <
notifications@github.com> wrote:

> For an application created to define words, using another individual's
> personal key is a serious issue. The proper way to go about this would
> be to install a dictionary.
>
> On 09/12/2015 04:59 PM, William Maduno | Diitto wrote:
> >
> > @JohnMHarrisJr <https://github.com/JohnMHarrisJr> LOL! As if that
> > matters! Please learn, you fool!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SethDusek/define/issues/16#issuecomment-139819724>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SethDusek/define/issues/16#issuecomment-139819827>.
>


-- 
- William Maduno | Diitto

**Comment by SethDusek** [comment]
"Define is a terminal dictionary script that uses wordnik for definitions"

Changing an API key would make no difference since wordnik would still give english definitions. Not providing an API key would provide nothing but inconvenience

**Comment by JohnMHarrisJr** [comment]
This is no complaint, this is an issue. This is not something that
effects only me, this effects all users of this program.

**Comment by JohnMHarrisJr** [comment]
Then, perhaps, you shouldn't use wordnik. You should either find another
service, or simply install a dictionary of your own.

**Comment by Diitto** [comment]
Well, then. Go find some other program to use. It's not as if you have to
use define, and it's not like the other users of define care about your
ideals. You have no reason to care for the other users of define, either.

On Saturday, September 12, 2015, John M. Harris, Jr. <
notifications@github.com> wrote:

> This is no complaint, this is an issue. This is not something that
> effects only me, this effects all users of this program.
>
> On 09/12/2015 05:03 PM, William Maduno | Diitto wrote:
> > Then do it yourself, silly! Are you not a developer? Or just too crappy
> of
> > one? If you don't feel like it, then don't make complaints, imbecile! :D
> >
> > On Saturday, September 12, 2015, John M. Harris, Jr. <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > For an application created to define words, using another individual's
> > > personal key is a serious issue. The proper way to go about this would
> > > be to install a dictionary.
> > >
> > > On 09/12/2015 04:59 PM, William Maduno | Diitto wrote:
> > > >
> > > > @JohnMHarrisJr <https://github.com/JohnMHarrisJr> LOL! As if that
> > > > matters! Please learn, you fool!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > <https://github.com/SethDusek/define/issues/16#issuecomment-139819724>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/SethDusek/define/issues/16#issuecomment-139819827
> >.
> > >
> >
> >
> > --
> > - William Maduno | Diitto
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SethDusek/define/issues/16#issuecomment-139819904>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SethDusek/define/issues/16#issuecomment-139829693>.
>


-- 
- William Maduno | Diitto

**Comment by Diitto** [comment]
Note that it would only require changing only *one* variable to change the
API key. If users don't want to use @SethDusek's API key, so be it. It's
not like this is proprietary software with the API key hard wired into the
program.

On Saturday, September 12, 2015, John M. Harris, Jr. <
notifications@github.com> wrote:

> Then, perhaps, you shouldn't use wordnik. You should either find another
> service, or simply install a dictionary of your own.
>
> On 09/12/2015 05:03 PM, SethDusek wrote:
> >
> > "Define is a terminal dictionary script that uses wordnik for
> definitions"
> >
> > Changing an API key would make no difference since wordnik would still
> > give english definitions. Not providing an API key would provide
> > nothing but inconvenience
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SethDusek/define/issues/16#issuecomment-139819909>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SethDusek/define/issues/16#issuecomment-139829707>.
>


-- 
- William Maduno | Diitto

**Comment by JohnMHarrisJr** [comment]
I do not personally use "define", but this is an issue, and it is valid.
It was closed, because the developers are to narrow minded to accept
that this project is, currently, failing to provide a basic dictionary
to users. It would, currently, be more helpful to download the entirety
of Websters English Dictionary to my disk, than to install this Python
script.

**Comment by shaggytwodope** [comment]
@JohnMHarrisJr It's nice you have an opinon, but it's just your own personal views here. As you do not even use define, this subject shouldn't even apply to you. I will however suggest you go buy a dictionary at your local bookshop. Since api keys and privacy is so important to you.

While the type of program define is does not match up with your ideals, it doesn't make that the case for everyone. Respect others freedom and stop with these posts.

**Comment by JohnMHarrisJr** [comment]
You assume that I have an issue with the software itself, I do not. It's
nice that SethDusek5 created something interesting, but this is not the
way to go about it. This is a simple script, to do what many other
projects have done properly.

The issue stated here is no opinion. This project currently uses an API
key that is hard-coded into the project. It was said that it would be
possible to use wordnik without the API key, so that's what I'm asking for.

**Comment by SethDusek** [comment]
@JohnMharrisJr Yep it sure would be. Let's see what would happen if I run

>cat dict.txt | grep test

https://gist.github.com/SethDusek/1db141491bdd74063b73

I would use dict but it returns loads and loads of (sometimes irrelevant) definitions, and the manpages do not seem to mention how one could limit the definitions.
https://gist.github.com/SethDusek/fa5a14cb873cc5a28e02

**Comment by JohnMHarrisJr** [comment]
The answer seems quite obvious, it's simple text parsing. I suggest you
make a new branch of define, and give this a try. :)

**Comment by SethDusek** [comment]
Maybe, but it most likely won't be the primary dictionary, maybe a fallback + a flag to use it

**Comment by JohnMHarrisJr** [comment]
It should be the default, and there should be multiple dictionaries (for
every language supported). If you need audio, you can synthesize using
GNUstep or similar software.

**Comment by SethDusek** [comment]
Just to update on this, define can parse the gcide dictionary for the DICT protocol, and also has support for WordNet, both using http (by the textblob module) and locally (using the wn program). If the local flag is set, it will use espeak for audio instead of downloading from wordnik.

**Comment by JohnMHarrisJr** [comment]
There should be no network requests, for any part of this software other
than Urban Dictionary "definitions."

**Comment by SethDusek** [comment]
No, they will stay. Wordnik will stay, bighugelabs thesaurus will stay and so will urban dictionary

**Comment by JohnMHarrisJr** [comment]
There is no use for Wordnik, you've already included a proper dictionary.

**Comment by SethDusek** [comment]
No, wordnik has more detailed definitions compared to wordnet. In the future there will be a config file though that will let you select default dictionary

**Comment by JohnMHarrisJr** [comment]
You should be using neither "wordnick" nor "wordnet", but dictionary
files that you download to the client's computer with your application,
or separately as libraries.

**Comment by SethDusek** [comment]
WordNet can be local or using http. If you have the textblob python module installed, it will use http. If it detects the wn (WordNet) program, it will use that instead, which is local.

Parsing local dictionaries is a pain in the ass as each outputs differently

**Comment by JohnMHarrisJr** [comment]
It should use neither, it should parse a dictionary file that you create
for this program specifically, or following some standard that I,
obviously, don't know about. Perhaps, just StarDict format.

**Comment by SethDusek** [comment]
I'm locking this since you're incredibly dense and still think that wordnik spies on you. They have no reason to, and I even talked to the developer about it. And even if they did, what words do you search that you feel uncomfortable sharing?
