### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by JohnMH** [SethDusek/define#17]
In this code, it is assumed that the user wants the English definition. Perhaps this could be fixed by using the system dictionary?

**Comment by professorjamesmoriarty** [comment]
For now the focus will remain english.

**Comment by JohnMH** [comment]
Perhaps the name should be changed to define-english, in that case. It would more accurately describe this project.

On August 26, 2015 7:36:56 AM EDT, Johnathan Jenkins notifications@github.com wrote:

> For now the focus will remain english.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SethDusek/define/issues/17#issuecomment-134957779

## 

Sent from my Android device. Please excuse my brevity.

**Comment by sethdusek** [comment]
Would you be happy if we changed the readme to say that it is an english dictionary?

**Comment by JohnMH** [comment]
No, but that would be a step towards the right thing to do.
