### ISSUE TITLE
HTTP use causes privacy issues

### ISSUE THREAD

**Issue by JohnMHarrisJr** [SethDusek/define#22]
This software, needlessly, uses a website to define words. This is a privacy issue, for many obvious reasons. The first of which is a simple MITM attack, and the worst of which is data collected by the service used itself. There are, at least, access logs containing the users' IP addresses, and SethDusek5, himself, says that stats are collected on the words users define.

This also brings up issues where this project is wasting bandwidth, making HTTP requests when you could obviously just look for the definition in a file easily.

**Comment by SethDusek** [comment]
A) You misinterpreted what I said. Words are collected anonymously and are used for statistics
B) How much bandwidth? 10kb? 20kb? I live in a 3rd world country and bandwidth is no issue for me. At all.
C) So what if your http request is intercepted?

**Comment by shaggytwodope** [comment]
Your welcome to your views and personal choices in what software you use. But stop spaming and demanding people change the nature of this to fit your own views. 

You can and are welcome to fork this project and do what YOU want. Within reason to the license used.
