### ISSUE TITLE
HTTP issues, that are real and need to be addressed rather than ignored

### ISSUE THREAD

**Issue by JohnMHarrisJr** [SethDusek/define#23]
Hi, I've already opened 3 issues but am not satisfied, even though define supports local wordnet and also gcide for the dict protocol.

**Comment by SethDusek** [comment]
A) How? First off, it's just words. Tell me, why are you uncomfortable with it collecting words. What words could you possibly search that you are not comfortable sharing?
B) You don't even use define. Also why would you use define on your pi and not your main machine?
C) Yup, the word they send, their ip adress and some headers.

They aren't real issues, out of all the people that have seen the project and used it, the only person that has complained is you. I added support for local dictionaries, add an alias and you can say goodbye to using wordnik. You've opened 4 issues by far about one big nothing, which has been solved and I would like to put behind now

**Comment by TeenageThrowawayV2** [comment]
I have seen the "path" of your "issues" with this over time. I would honestly agree here with @shaggytwodope that you are spamming. Opening up MULTIPLE issues, after discussion has happened on all of them about how this is totally fine to do.

Plus, why not fork define yourself and remove any reference at all to Wordnik?

Also, I guess you should stop using Github (and any other website out there ever) too! Since if your HTTP request is intercepted, you've just given up information on the user, their IP address and possibly much more! Oh no!

Now, please. Shut up. I made a Github account just to comment this. Thank you, and goodbye.

**Comment by JohnMHarrisJr** [comment]
Let's stop the A) B) C) format.

Collection of users' queries is a serious issue, and it can't just be ignored. It doesn't matter what words people are searching, they're being logged.

I don't, personally, use define, but apparently there are people who do and this isn't fair to them.

As for your "C", you're even admitting that this is an issue. Please fix it, and stop ignoring this and closing the issues.

**Comment by JohnMHarrisJr** [comment]
@TeenageThrowawayV2 I use the Tor Browser to browse the web interface of
GitHub, and normally I use the email gateway to take part in
conversations discussing issues that I report.

**Comment by SethDusek** [comment]
It is fair to them, it uses wordnik and they know that, since it's in the first sentence of the readme. I didn't force them to use my project, they use it willingly, and they know what is going on, and they probably do not care. You also are free to use define, or not to. And I don't know whether you've read this the dozens of  times I've mentioned it, but you can use local dictionary with define, wordnet and gcide. So please stop opening issues again and again.

**Comment by JohnMHarrisJr** [comment]
You, now, have the 'option' to use a local dictionary, but it is not the
default behavior. There is no sense in using the internet to define a
word, when downloading a dictionary is better in every way, including
that it doesn't make an HTTP request every time you need to define a
word, causing serious privacy issues. Does this project even use the
system proxy?

**Comment by TeenageThrowawayV2** [comment]
@JohnMHarrisJr But you still use your (almost) full name, picture, and personal information splattered over the web.

Dude just... Just don't pay attention to the project. Report the problem ONCE, and go on about your life. Opening multiple issues is is just plain idiotic. Now please, this has been discussed. So please SHUT UP.

**Comment by SethDusek** [comment]
Yup. You feel uncomfortable about words being logged but have disclosed:
Your name
Your email
Where you were born (scotland)
What you look like
Which country you live in
And much more. Yet logging ip adresses is bad?

**Comment by TeenageThrowawayV2** [comment]
Plus, @JohnMHarrisJr , if someone has access of ANY of the TOR nodes that you go through, they have all your information anyway. So, what's the problem that?

**Comment by JohnMHarrisJr** [comment]
@TeenageThrowawayV2 While I use my name and picture, there is no
personal information about me on the internet, other than the fact that
I am male and that, at some point in time, I signed up for an email
account over at OpenMailBox.

I reported this issue, and it was ignored and then closed. This is an
issue, so it needs to stay open until resolved or closed with a
"wontfix" tag, the latter being the simpleton's way out.

**Comment by TeenageThrowawayV2** [comment]
@JohnMHarrisJr So you act like a child not getting their way? Quite hilarious, really.

**Comment by JohnMHarrisJr** [comment]
@SethDusek If you would like to believe I was born in Scotland, that's
your belief. I suggest that you don't make any bets on that, and I also
suggest that you don't rely on any information provided about myself.

**Comment by SethDusek** [comment]
I don't think that github or any other site should know what gender you are, as it is a violation of your privacy.

**Comment by JohnMHarrisJr** [comment]
@TeenageThrowawayV2 Obviously you don't know how Tor works, Tor has
end-to-end encryption, and I would never visit a website that doesn't
use HTTPS over Tor. Nobody on the Tor network, nor elsewhere on the
internet, has much information about me.

This issue is not about me, it is about this software. Please move the
conversation back to 'define.'

**Comment by tirkaz** [comment]
@JohnMHarrisJr 

This conversation is not about the software. It's long been about you and your inability to understand that what you perceive as an issue isn't an issue to the vast majority of those who use this software. Not only that, but you are free to fork and fix it. You just refuse to.

**Comment by TeenageThrowawayV2** [comment]
Oh and @JohnMHarrisJr -- The NSA has cracked Tor already. Probably multiple times.

Plus, this issue has already been talked about and resolved.

@SethDusek Would you mind PLEASE closing the thread in a bit?

**Comment by JohnMHarrisJr** [comment]
*@tirkaz* This conversation is about an issue with this software, that
needs to be resolved. I cannot help "the vast majority" and their lack
of perception of security issues. I have no desire to fix this software.
My duty to society doesn't include fixing every bit of software with an
issue.

I would never write anything in Python, I personally hate the language.
Even if this were written in Java, C, C++, Lua, Javascript or another
language that I know well, it isn't my job to fix issues in this
project. It isn't my project.

**Comment by TeenageThrowawayV2** [comment]
@JohnMHarrisJr Why not just, oh I don't know, MOVE ON WITH YOUR LIFE, THEN?!

**Comment by JohnMHarrisJr** [comment]
I will ignore further conversation on this issue, if it does not pertain
to the project.

**Comment by TeenageThrowawayV2** [comment]
Nor does what you have been saying, @JohnMHarrisJr -- Goodbye.
