### ISSUE TITLE
HTTP issues

### ISSUE THREAD

**Issue by JohnMHarrisJr** [SethDusek/define#24]
This issue is, actually, #16 , #22 and #23 but they were closed by the childish maintainer of this project. No need to add a proper description, just read those, other than #23 which was changed by the aforementioned childish maintainer.

**Comment by SethDusek** [comment]
I'm not a child. I'll have you know that in 2015 i turned 10 years old which is a mature age

**Comment by JohnMHarrisJr** [comment]
This is not "invalid", though it is certainly a duplicate.

**Comment by BrigDan** [comment]
More than a duplicate.

**Comment by JohnMHarrisJr** [comment]
This is a real issue, and should not be closed.

**Comment by SethDusek** [comment]
No.

**Comment by JohnMHarrisJr** [comment]
Yes, please open this issue.

**Comment by SethDusek** [comment]
No.

**Comment by JohnMHarrisJr** [comment]
Please open this issue, and leave it that way until resolved.

**Comment by SethDusek** [comment]
It isn't an issue. we've been over that already

**Comment by JohnMHarrisJr** [comment]
It is an issue, even by your definition, and needs to be opened until fixed.

**Comment by SethDusek** [comment]
No. I already told you that wordnik does not collect ips or data. Sure they collect the frequency of words for what I'm guessing is statistics, but why do you have an issue against a site increasing a number depending on your query?

**Comment by JohnMHarrisJr** [comment]
The fact that they track anything is a privacy concern, and should be
avoided. There's no sense in making HTTP requests for definitions, anyway.

**Comment by SethDusek** [comment]
It really really really isn't
