### ISSUE TITLE
Support for multiple definitions

### ISSUE THREAD

**Issue by cdlscpmv** [SethDusek/define#36]
Almost all words are not limited to one definition. And usually the Wordnik web-interface shows a few of them alongside with the corresponding part of speech. It would be nice for this program to do the same.

**Comment by professorjamesmoriarty** [comment]
@cdlscpmv What do you have in mind in terms of how to do this. I think it may be worth doing this, but as an option perhaps?

@SethDusek Thoughts?

**Comment by cdlscpmv** [comment]
It may be an option which would be needed only if the first definition was not satisfactory. But, on the other hand, how do you know, without looking at other definitions, that the first definition given is the most accurate one for a particular situation? I've been using Wordnik for a long time, and I often take a glance at multiple definitions to choose the most accurate one (from my point of view) for my particular case. So I see no reason not to show all definitions for a word together.

I don't know much about the Wordnik API, but if it lets you get a word with the corresponding part of speech, then showing that part of speech in front of the corresponding definition would be enough. A part of speech can be shortened to one or more letters (like it is done in the Wordnik web-interface) and put into square brackets, for example.

**Comment by sethdusek** [comment]
Will work on this, thanks

**Comment by sethdusek** [comment]
Added multi definition support, tweak the max_definitions variable, which is by default 3

**Comment by cdlscpmv** [comment]
Thanks!
