### ISSUE TITLE
Audio does not work

### ISSUE THREAD

**Issue by nixi-awoo** [SethDusek/define#5]
I get this error whilst using the --audio flag:

```
bash: play: command not found
```

I suggest using [mplayer](https://wiki.archlinux.org/index.php/MPlayer), which can fetch the audio file by itself without the need of wget.
If mplayer is out of the question, fix the package dependencies.

**Comment by professorjamesmoriarty** [comment]
Sox dependacy for play added to the AUR package. Please try to mention source and method of install in the future.
